const K="kidsMoneyLabV2",MK="kidsMoneyMarketV2";const A={cash:{name:"貯金",kid:"ためる",icon:"🏦",rate:.002,risk:"小"},world:{name:"全世界株式",kid:"せかいの かぶ",icon:"🌎",rate:.055,risk:"大"},sp:{name:"S&P500",kid:"アメリカの かぶ",icon:"🇺🇸",rate:.06,risk:"大"}};let S=load(),sel=S.children[0].id,M=loadM(),kid=localStorage.getItem("kidsMoneyKidMode")==="1";
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID?.()||Date.now()+Math.random(),yen=n=>"¥"+Math.round(n||0).toLocaleString("ja-JP"),esc=s=>String(s??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[x])),save=()=>localStorage.setItem(K,JSON.stringify(S)),loadM=()=>{try{return JSON.parse(localStorage.getItem(MK))||{}}catch{return{}}},saveM=()=>localStorage.setItem(MK,JSON.stringify(M));
function load(){try{let x=JSON.parse(localStorage.getItem(K));if(x?.version===2&&x.children?.length)return x}catch{}return{version:2,children:[{id:uid(),name:"こどもA",birthYear:2019,transactions:[],goals:[]}]}}
function ch(){return S.children.find(x=>x.id===sel)}function calc(x){let b={cash:0,world:0,sp:0},cost=0,ins=0,outs=0;x.transactions.forEach(t=>{let a=+t.amount||0;if(t.type==="out"){outs+=a;b[t.asset]=Math.max(0,b[t.asset]-a)}else{ins+=a;b[t.asset]+=a;if(t.asset!=="cash")cost+=a}});let w=M.world?.indexValue&&M.world?.baseIndex?b.world*M.world.indexValue/M.world.baseIndex:b.world,s=M.sp?.indexValue&&M.sp?.baseIndex?b.sp*M.sp.indexValue/M.sp.baseIndex:b.sp;return{b,cost,ins,outs,inv:w+s,total:b.cash+w+s,w,s}}
function render(){let z=calc(ch());$("child").innerHTML=S.children.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("");$("child").value=sel;$("total").textContent=yen(z.total);$("cash").textContent=yen(z.b.cash);$("invest").textContent=yen(z.inv);$("ins").textContent=yen(z.ins);$("outs").textContent=yen(z.outs);$("pnl").textContent=(z.inv-z.cost>=0?"+":"-")+yen(Math.abs(z.inv-z.cost));$("note").textContent=kid?"ぜんぶの おかね":`投資元本 ${yen(z.cost)} · 損益 ${(z.inv-z.cost>=0?"+":"-")+yen(Math.abs(z.inv-z.cost))}`;
$("assets").innerHTML=Object.entries(A).map(([k,a])=>{let v=k==="cash"?z.b.cash:k==="world"?z.w:z.s,c=k==="cash"?0:z.b[k];return`<article class="asset"><div class="assettop"><span class="asseticon">${a.icon}</span><span>${kid?(a.risk==="小"?"へりにくい":"へることもある"):"リスク："+a.risk}</span></div><h3>${kid?a.kid:a.name}</h3><div class="value">${yen(v)}</div><div class="meta">${kid?(k==="cash"?"いま ためている おかね":"いれた おかね "+yen(c)+" · "+(v>=c?"ふえた ":"へった ")+yen(Math.abs(v-c))):(k==="cash"?"残高":"元本 "+yen(c)+" · 損益 "+(v-c>=0?"+":"-")+yen(Math.abs(v-c)))}</div></article>`}).join("");
renderTx();renderGoals();renderM();draw();crash()}
function renderTx(){let f=$("tf").value,a=$("af").value,t=ch().transactions.filter(x=>(f==="all"||x.type===f)&&(a==="all"||x.asset===a)).sort((x,y)=>y.date.localeCompare(x.date));$("txs").innerHTML=t.length?t.map(x=>`<div class="card"><b>${x.date} · ${x.type==="in"?"＋":"−"}${yen(x.amount)}</b><div>${esc(x.reason)} · ${A[x.asset].icon} ${kid?A[x.asset].kid:A[x.asset].name}</div></div>`).join(""):'<div class="card muted">きろくが ありません。</div>'}
function renderGoals(){$("goals").innerHTML=(ch().goals||[]).map(g=>{let p=Math.min(100,Math.round(g.saved/g.amount*100));return`<div class="goal"><h3>${esc(g.name)}</h3><div class="goalmeta"><span>${yen(g.saved)} / ${yen(g.amount)}</span><span>${g.date}</span></div><div class="goalbar"><span style="width:${p}%"></span></div><div class="goalmeta"><span>${p}%</span><span>あと ${yen(g.amount-g.saved)}</span></div></div>`}).join("")||'<div class="card muted">めあてを つくってみよう。</div>'}
function renderM(){let n={world:"🌎 "+(kid?"せかいの かぶ":"全世界株式"),sp:"🇺🇸 "+(kid?"アメリカの かぶ":"S&P500")};$("market").innerHTML=["world","sp"].map(k=>{let m=M[k];return`<div class="market"><div class="mhead"><span>${n[k]}</span>${m?`<span class="${m.change>=0?"up":"down"}">${m.change>=0?"+":""}${m.change.toFixed(2)}%</span>`:""}</div><div class="price">${m?Number(m.indexValue).toLocaleString():"未取得"}</div></div>`}).join("")}
async function refresh(){try{let [a,b]=await Promise.all([fetch("https://query1.finance.yahoo.com/v8/finance/chart/ACWI?range=5d&interval=1d"),fetch("https://query1.finance.yahoo.com/v8/finance/chart/%5EGSPC?range=5d&interval=1d")]);if(!a.ok||!b.ok)throw 0;let p=j=>{let r=j.chart.result[0],c=r.indicators.quote[0].close.filter(Boolean),v=c.at(-1),q=c.at(-2)||v;return{indexValue:v,change:(v/q-1)*100,updated:new Date().toISOString()}};let w=p(await a.json()),s=p(await b.json());w.baseIndex=M.world?.baseIndex||w.indexValue;s.baseIndex=M.sp?.baseIndex||s.indexValue;M={world:w,sp:s,updated:new Date().toISOString()};saveM();render()}catch{$("marketStatus").textContent="取得できませんでした。あとで もういちど。"}}
function tx(type){$("txType").value=type;$("txTitle").textContent=type==="in"?"おかねを いれる":"おかねを つかう";$("date").value=new Date().toISOString().slice(0,10);$("asset").innerHTML=Object.entries(A).map(([k,a])=>`<option value="${k}">${a.icon} ${kid?a.kid:a.name}</option>`).join("");$("txModal").classList.remove("hidden")}
function close(id){$(id).classList.add("hidden")}function open(id){$(id).classList.remove("hidden")}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));$(b.dataset.tab).classList.add("active")});
$("child").onchange=e=>{sel=e.target.value;render()};$("addChild").onclick=()=>open("childModal");$("settings").onclick=()=>open("settingsModal");$("in").onclick=$("in2").onclick=()=>tx("in");$("out").onclick=$("out2").onclick=()=>tx("out");$("refresh").onclick=refresh;$("tf").onchange=renderTx;$("af").onchange=renderTx;$("kidMode").onchange=e=>{kid=e.target.checked;localStorage.setItem("kidsMoneyKidMode",kid?1:0);render()};
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>close(b.dataset.close));
$("childForm").onsubmit=e=>{e.preventDefault();let q={id:uid(),name:$("childName").value,birthYear:+$("birth").value,transactions:[],goals:[]};S.children.push(q);sel=q.id;save();close("childModal");e.target.reset();render()};
$("txForm").onsubmit=e=>{e.preventDefault();let x=ch(),type=$("txType").value,a=+$("amount").value,asset=$("asset").value,z=calc(x);if(type==="out"&&a>z.b[asset])return alert("のこっている おかねより おおきいよ。");x.transactions.push({id:uid(),type,date:$("date").value,amount:a,reason:$("reason").value,asset,memo:$("memo").value});save();close("txModal");e.target.reset();render()};
$("addGoal").onclick=()=>open("goalModal");$("goalForm").onsubmit=e=>{e.preventDefault();ch().goals.push({id:uid(),name:$("goalName").value,amount:+$("goalAmount").value,date:$("goalDate").value,saved:+$("goalSaved").value||0});save();close("goalModal");e.target.reset();render()};
function ratio(){let s=+$("saveRatio").value;$("investRatio").value=100-s;$("sr").textContent=s+"%";$("ir").textContent=100-s+"%"}$("saveRatio").oninput=ratio;$("investRatio").oninput=()=>{$("saveRatio").value=100-$("investRatio").value;ratio()};
$("simulate").onclick=()=>{let z=calc(ch()),cur=z.total,a=+$("annual").value,y=+$("years").value,s=+$("saveRatio").value/100,f=(p,n,r)=>r===0?p+n*y:p*Math.pow(1+r,y)+n*(Math.pow(1+r,y)-1)/r,v=f(cur*s,a*s,.002)+f(cur*(1-s),a*(1-s),.055);$("result").innerHTML=`<div class="card"><h3>かんがえてみよう</h3><div class="value">${yen(v)}</div><p class="muted">${y}ねん後 · ためる ${s*100}% / ふやす ${(1-s)*100}%</p><p>これは よそうの けいさんだよ。ほんとうの投資では ふえることも へることも あるよ。</p></div>`};
function crash(){let z=calc(ch()),d=+$("crash").value;$("crashL").textContent="-"+d+"%";$("crashBox").textContent=yen(z.inv)+" → "+yen(z.inv*(1-d/100)+z.b.cash)}
$("crash").oninput=crash;$("export").onclick=()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:"application/json"}));a.download="kids-money-v2-backup.json";a.click()};$("import").onchange=e=>{let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(x.version!==2||!x.children.length)throw 0;S=x;sel=S.children[0].id;save();close("settingsModal");render()}catch{alert("JSONが正しくありません")}};r.readAsText(e.target.files[0])};$("reset").onclick=()=>{if(confirm("データを ぜんぶ けしていい？")){localStorage.removeItem(K);S=load();sel=S.children[0].id;render()}};
function draw(){let c=$("chart"),x=c.getContext("2d"),w=c.clientWidth||600,h=220,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);x.fillStyle="#687386";x.font="13px sans-serif";x.fillText(ch().transactions.length?"":"おかねを いれると うごきが みえるよ",15,35)}window.onresize=draw;render();ratio();