"use strict";
/* V32.1 quiz: random question pool + child-specific history. */
(function(){
 const Q=[
 {id:"save-01",title:"ためる",q:"おこづかいを すぐにつかわず、あとでつかうために のこすことは？",k:"おかねを のこして おくことは？",c:["ためる","なくす","すてる"],a:0,e:"つかわずに のこすことを 貯金（ちょきん）といいます。",ke:"おかねを のこして おくことを ためると いうよ。"},
 {id:"need-01",title:"ひつようなもの",q:"毎日の生活に必要なものは、どれ？",k:"まいにち ひつようなものは？",c:["ごはん","ゲームを100こ","おもちゃを100こ"],a:0,e:"食べものなど、生活に必要なものがあります。",ke:"ごはんなど、くらしに ひつようなものが あるよ。"},
 {id:"want-01",title:"ほしいもの",q:"ほしいものにお金を使う前に大切なことは？",k:"ほしいものを かうまえに たいせつなことは？",c:["お金があるか考える","全部買う","お金を数えない"],a:0,e:"使えるお金を確認してから考えるのが大切です。",ke:"つかえる おかねを かくにんしてから かんがえよう。"},
 {id:"risk-01",title:"とうし",q:"投資では、どうなることがある？",k:"とうしの おかねは どうなることが ある？",c:["増えることも減ることもある","必ず増える","絶対に変わらない"],a:0,e:"投資には値上がりと値下がりがあります。",ke:"とうしは ふえることも へることも あるよ。"},
 {id:"div-01",title:"わける",q:"お金をいくつかに分ける考え方は？",k:"おかねを いくつかに わける かんがえかたは？",c:["分散","全部使う","放置"],a:0,e:"分散すると、一つだけに頼るリスクを減らせます。",ke:"いくつかに わけると、ひとつだけに たよる きけんを へらせるよ。"},
 {id:"interest-01",title:"ふえる",q:"1000円をためて少しずつ増える仕組みを何という？",k:"1000えんが すこしずつ ふえる しくみは？",c:["利息","買い物","おつり"],a:0,e:"預金などでは利息がつくことがあります。",ke:"おかねを あずけると りそくが つくことが あるよ。"},
 {id:"budget-01",title:"よさん",q:"使うお金と、ためるお金を先に決めることは？",k:"つかう おかねと ためる おかねを さきに きめることは？",c:["予算を立てる","全部使う","何も考えない"],a:0,e:"予算を決めると、お金の使い方を考えやすくなります。",ke:"つかう おかねを さきに きめると かんがえやすいよ。"},
 {id:"price-01",title:"ねだん",q:"同じ商品でも店によって値段が違うときは？",k:"おなじものでも おみせで ねだんが ちがうときは？",c:["比べて選べる","必ず高い店で買う","値段を見ない"],a:0,e:"値段や内容を比べて選ぶことができます。",ke:"ねだんを くらべて えらべるよ。"},
 {id:"goal-01",title:"めあて",q:"ほしいもののために必要なお金を少しずつためるのは？",k:"ほしいもののために おかねを すこしずつ ためるのは？",c:["目標を決めてためる","全部使う","あきらめる"],a:0,e:"目標金額と期限を決めると続けやすくなります。",ke:"めあてと きげんを きめると つづけやすいよ。"},
 {id:"tax-01",title:"おかねのルール",q:"商品を買ったとき、商品代とは別にかかることがあるものは？",k:"かいものをしたとき、べつに かかることが あるものは？",c:["消費税","宿題税","ゲーム税"],a:0,e:"日本では買い物などに消費税がかかります。",ke:"にほんでは かいものなどに しょうひぜいが かかるよ。"}
 ];
 let current=null;
 let lastQuestionId=null;
 const km=()=>window.KidsMoney, kid=()=>km()?.isKidMode?.()||false, child=()=>km()?.getCurrentChild?.(), esc=v=>km()?.escapeHtml?.(v)||String(v??'');
 function learning(){const c=child();if(!c)return null;c.learning=c.learning&&typeof c.learning==='object'?c.learning:{};c.learning.history=Array.isArray(c.learning.history)?c.learning.history:[];c.learning.seenQuizIds=Array.isArray(c.learning.seenQuizIds)?c.learning.seenQuizIds:[];c.learning.quizAnswered=Number(c.learning.quizAnswered||0);c.learning.quizCorrect=Number(c.learning.quizCorrect||0);c.learning.streak=Number(c.learning.streak||0);c.learning.bestStreak=Number(c.learning.bestStreak||0);return c.learning;}
 function pick(){const l=learning();if(!l)return null;let u=Q.filter(x=>!l.seenQuizIds.includes(x.id) && x.id!==lastQuestionId);if(!u.length){if(Q.length>1){l.seenQuizIds=[];u=Q.filter(x=>x.id!==lastQuestionId);}else{l.seenQuizIds=[];u=Q.slice();}}return u[Math.floor(Math.random()*u.length)];}
 function render(){const box=document.getElementById('learn');if(!box)return;const l=learning();if(!l)return;const q=current||pick();current=q;lastQuestionId=q?.id||lastQuestionId;if(!q)return;const isKid=kid();const choices=q.c.map((x,i)=>`<button class="quiz-choice" type="button" data-answer="${i}">${esc(isKid?kidChoice(x):x)}</button>`).join('');box.innerHTML=`<div class="section-header"><div><h2>${isKid?'おかね クイズ':'お金クイズ'}</h2><p class="muted">${esc(q.title)}</p></div><button class="secondary" id="nextQuiz" type="button">${isKid?'🔄 つぎの もんだい':'🔄 別の問題'}</button></div><div class="quiz-card"><div class="quiz-number">🎯</div><h3>${esc(isKid?q.k:q.q)}</h3><div class="quiz-choices">${choices}</div><div id="quizResult"></div></div>${historyHtml(l)}`;}
 function historyHtml(l){const isKid=kid();return `<section class="card quiz-history"><div class="section-header"><h3>${isKid?'📖 こたえた きろく':'📖 クイズ履歴'}</h3><span>${l.quizAnswered}${isKid?'もん':'問'}</span></div>${l.history.length?l.history.slice().reverse().slice(0,20).map(h=>`<div class="study-history"><span>${esc(h.date||'')}</span><span>${esc(h.title||'クイズ')}</span><strong>${h.correct?'⭕':'❌'}</strong></div>`).join(''):`<p class="muted">${isKid?'まだ きろくが ないよ。':'まだクイズ履歴がありません。'}</p>`}</section>`;}
 function kidChoice(x){const m={"お金があるか考える":"おかねが あるか かんがえる","全部買う":"ぜんぶ かう","お金を数えない":"おかねを かぞえない","増えることも減ることもある":"ふえることも へることも ある","必ず増える":"かならず ふえる","絶対に変わらない":"かわらない","分散":"わける","全部使う":"ぜんぶ つかう","放置":"そのまま","利息":"りそく","買い物":"かいもの","予算を立てる":"よさんを たてる","何も考えない":"なにも かんがえない","比べて選べる":"くらべて えらべる","必ず高い店で買う":"たかい おみせで かう","值段を見ない":"ねだんを みない","値段を見ない":"ねだんを みない","目標を決めてためる":"めあてを きめて ためる","消費税":"しょうひぜい","宿題税":"しゅくだいぜい","ゲーム税":"ゲームぜい"};return m[x]||x;}
 function answer(i){if(!current)return;const l=learning(),ok=i===current.a;if(!l.seenQuizIds.includes(current.id))l.seenQuizIds.push(current.id);l.quizAnswered++;if(ok){l.quizCorrect++;l.streak++;l.bestStreak=Math.max(l.bestStreak,l.streak);}else l.streak=0;l.lastQuizDate=km().getToday();l.history.push({date:l.lastQuizDate,questionId:current.id,title:current.title,correct:ok});l.history=l.history.slice(-100);km().saveState();const r=document.getElementById('quizResult');if(r)r.innerHTML=`<div class="quiz-result ${ok?'correct':'wrong'}"><strong>${ok?(kid()?'⭕ せいかい！':'⭕ 正解です！'):(kid()?'❌ ちがうよ':'❌ 不正解です')}</strong><p>${esc(kid()?current.ke:current.e)}</p><button class="primary" id="nextQuiz2" type="button">${kid()?'つぎへ':'次の問題'}</button></div>`;document.querySelectorAll('.quiz-choice').forEach(b=>b.disabled=true);}
 document.addEventListener('click',e=>{const a=e.target.closest('[data-answer]');if(a)answer(Number(a.dataset.answer));if(e.target.closest('#nextQuiz')||e.target.closest('#nextQuiz2')){current=null;render();}});
 window.KidsMoneyLearn={render,next:()=>{current=null;render();},getQuestions:()=>Q};window.refreshLearnForModeChange=()=>{current=null;render();};window.addEventListener('kidsMoneyChildChanged',()=>{current=null;render();});window.addEventListener('kidsMoneyKidModeChanged',()=>{current=null;render();});
})();
